export const TOGGLE_LOADING = 'TOGGLE_LOADING'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const  TOGGLE_DEVICE = "TOGGLE_DEVICE"

export const EXPAND_MENU = 'EXPAND_MENU'

export const SWITCH_EFFECT = 'SWITCH_EFFECT'

export const LOAD_MENU = 'LOAD_MENU'
export const SET_USER_INFO = 'SET_USER_INFO'
