const types = {
  TOGGLE_LOADING: 'TOGGLE_LOADING',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  TOGGLE_SIDEBAR_SHOW: 'TOGGLE_SIDEBAR_SHOW',
  TOGGLE_DEVICE: "TOGGLE_DEVICE",
  EXPAND_MENU: 'EXPAND_MENU',
  SWITCH_EFFECT: 'SWITCH_EFFECT',
  LOAD_MENU: 'LOAD_MENU',
  LOAD_CURRENT_MENU: 'LOAD_CURRENT_MENU',
  SET_USER_INFO: 'SET_USER_INFO',
}

export default types
